[package]
name = "sat_solver"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
global_counter = "0.2.2"
tailcall = "1.0.1"
